version: '3'
services:
    spark:
      image: bitnami/spark:2.4.4
      ports:
        - "8080:8080"
        - "7077:7077"
    emr:
      build: .
      ports:
        - "3000:3000"
    livy:
      image: cloudiator/livy-server:melodic-stable
      restart: always
      ports:
        - "8998:8998"
      depends_on:
        - spark
      environment:
        - SPARK_MASTER_ENDPOINT=spark
        - SPARK_MASTER_PORT=7077
        - DEPLOY_MODE=client
