version: '3'
services:
  localemr:
    build: .
    container_name: localemr
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/localemr
  s3:
    container_name: s3
    image: motoserver/moto:latest
    command: ["s3", "-p2000"]
    ports:
      - "2000:2000"
