# GitHub Actions configuration
name: Local EMR CI

on: [push]

jobs:
  test-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack with the 'cluster' already running
      run: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml -f docker-compose.livy.yaml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Install test dependencies
      run:  docker-compose exec -T localemr pip install -r requirements-dev.txt
    - name: Run flake8
      run: docker-compose exec -T localemr flake8 localemr test
    - name: Run test suite
      run: docker-compose exec -T localemr pytest
  test-dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack without the 'cluster' running
        run: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml -f docker-compose.dynamic.yaml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Install test dependencies
        run:  docker-compose exec -T localemr pip install -r requirements-dev.txt
      - name: Run flake8
        run: docker-compose exec -T localemr flake8 localemr test
      - name: Run test suite
        run: docker-compose exec -T localemr pytest
  push-to-docker:
    needs: [test-static, test-dynamic]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Dockerhub
        uses: docker/build-push-action@v1
        if:  contains(github.ref, 'release')
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davlum/localemr
          tags: latest
