on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Release Tag
      id: gettag
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF:10})"
    - name: Build the docker-compose stack
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Run tests
      run:  docker-compose exec -T localemr ./check.sh
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build/Test and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/davlum/localemr:latest
          ghcr.io/davlum/localemr:${{ steps.gettag.outputs.tag }}
